### PR TITLE
fix: upgrade libraries-bom to 26.34.0 and add spanner support float32 type

### PR DESCRIPTION
**Pull request by zhumin8**
spanner client library added new feat https://github.com/googleapis/java-spanner/pull/2894 in v6.61.0, changes in spanner module accordingly to support it.

This change is covered by existing tests: `SpannerWriteMethodCoverageTests` and `SpannerStructReadMethodCoverageTests`. 
These tests checks that the converter is aware of **all** Spanner mutation binder types (to write) & struct getter types (to read). 

This should fix test failures in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2659#issuecomment-1985897118, and closes #2659.

Need to back-port to 4.x and 3.x branches

BEGIN_COMMIT_OVERRIDE
deps: bump com.google.cloud:libraries-bom from 26.33.0 to 26.34.0 

feat(spanner): support float32 type.
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by zhumin8** [comment]
it test failure:
```
Error: 9:503 [ERROR] Errors: 
Error: 9:503 [ERROR]   BigQueryFileMessageHandlerIntegrationTests.setup:74 » BigQuery Exceeded rate limits: too many table update operations for this table.
```

**Comment by JoeWang1127** [comment]
Could you add a unit test to verify the behavior, or why it can't be tested?

**Comment by zhumin8** [comment]
> Could you add a unit test to verify the behavior, or why it can't be tested?

Ah, good point. I'll add them in.

**Comment by zhumin8** [comment]
@JoeWang1127 Can you please take another look?

**Review by JoeWang1127 — APPROVED** [review]

**Pull request merged**
