### PR TITLE
feat: remove `SecretManagerPropertySourceLocator`

### PR DESCRIPTION
**Pull request by JoeWang1127**
Fix https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1570

### CODE REVIEW

**Review by meltsufin — APPROVED** [review]
Since it's a public class, and there might be usage outside of the

**Comment by JoeWang1127** [comment]
> Since it's a public class, and there might be usage outside of the

Should we deprecate the class and remove it in the next major version?

**Comment by meltsufin** [comment]
> > Since it's a public class, and there might be usage outside of the
> 
> Should we deprecate the class and remove it in the next major version?

Oops, I didn't mean to send that. I started writing that and then changed my mind after looking more into the use of the class exclusively for bootstrap. We are still keeping the actual PropertySource. So, I think it's fine to remove.

**Comment by JoeWang1127** [comment]
Cool, then I'll proceed with the merge.

**Pull request merged**
