### PR TITLE
Resolve references descendants for subclasses

### PR DESCRIPTION
**Pull request by THCoulon**
I'm the same guy from the issue #356 

- I'm not an expert of this repository since I learned how to use it this week.
- I let you guys handle the correctness of this merge

### CODE REVIEW

**Comment by THCoulon** [comment]
@googlebot I signed it!

**Comment by THCoulon** [comment]
1.  Forgot to re-enable the linter (<maven-checkstyle-plugin.skip>false</maven-checkstyle-plugin.skip>)
2.  The CLA need to be confirmed for my company

**Comment by meltsufin** [comment]
@THCoulon Thanks for opening the PR, are you still waiting for confirmation on the CLA?

**Comment by THCoulon** [comment]
@googlebot I signed it!

**Comment by THCoulon** [comment]
Yep it's been signed today.

**Comment by THCoulon** [comment]
Finally ! I had some really big problems to use your coding style within Intellij.

I hope everything's okay

**Comment by meltsufin** [comment]
`DatastoreTemplateTests` seem to be failing. Also, can you please undo any formatting changes to code that you didn't modify? It makes it hard to review with all of those additional deltas. Thanks!

**Comment by THCoulon** [comment]
@meltsufin Thanks you for your time and patience !

> Also, can you please undo any formatting changes to code that you didn't modify? It makes it hard to review with all of those additional deltas

Just to be sure:

I imported this configuration [https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml](url) seen from [https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/CONTRIBUTING.md](url).

And then imported this configuration on top of the previous one [https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/src/eclipse/eclipse-code-formatter.xml](url).

Then I had to tweak a lot of parameters from the code styling configuration to make it compatible with your checkstyle plugin.

Did I do something wrong ?

But yeah I'll revert back to the previous commit and do the checking again and ensure that it doesn't modify your code. I totally understand that reviewing DatastoreTemplate in this state is a nightmare :hankey:.

> DatastoreTemplateTests seem to be failing

As we discussed in my issue. DatastoreTemplate is failing, Do you want me to modify the unit tests ? I was afraid to modify them because of misunderstanding the logic.

**Comment by ttomsu** [comment]
@THCoulon Apologies for the difficulty using the checkstyle formatter. We inherited that from when this project rolled up under the Spring Cloud organization and I, too, frequently run into issues with it. It's currently an important-but-not-urgent for us to roll that back and apply our own, preferably automated, way to ensure the code is formatted (sort of like `gofmt` if you've ever used that tool).

**Comment by THCoulon** [comment]
Something is still wrong ? I hope everything's fine :tada: 

I managed to fix everything. Yet, the new functionality is not tested inside the unit package.

> Apologies for the difficulty using the checkstyle formatter

It's just taking more time to format by hand instead of just simply formatting the whole project. Anyway, Thank you for you concern.

**Review by meltsufin — APPROVED** [review]
@THCoulon I added some more polish commits. See if you're OK with those changes.
Otherwise, the PR looks good from my end.
Thanks for the hard work digging through the Spring Data Datastore code, which is not intuitive at all, and ultimately needs to be refactored.

**Comment by THCoulon** [comment]
@meltsufin 100% Approved.

To be honest I need these modifications . Now they are in good hands.

**Pull request merged**
