### PR TITLE
Add more features to SecretManager

### PR DESCRIPTION
**Pull request by kioie**
Adding a delete Secrets  method to simplify the process of deleting secrets. This is an additional method to beef up features for the spring secret manager service.

### CODE REVIEW

**Comment by dzou** [comment]
@kioie - Thanks for the contribution! Very excited to see users start using this module.

Sorry to be an inconvenience; would you mind opening this PR against [our old repo](https://github.com/spring-cloud/spring-cloud-gcp)? We're not quite ready to start contributing to this one directly yet.

**Comment by kioie** [comment]
Yea...no worries!

**Comment by dzou** [comment]
Closing because this was moved to the old repo. Thanks again for the contribution!

**Comment by kioie** [comment]
Thanks @dzou moved [here](https://github.com/spring-cloud/spring-cloud-gcp/pull/2426)

**Pull request closed without merging**
