### PR TITLE
fix: regression of outbound pubsub message handling (success/failure callbacks both called regardless of success/failure)

### LINKED ISSUE #1799: Spring Boot 3 changes to PubSubPublishCallback have resulted in failure callback being called when operation was successful
**Describe the bug**
Recent `PubSubPublishCallback` changes results in pub sub outbound message handling calling both the success and failure callbacks, regardless of success or failure. This is confusing and a regression from previous behaviour.

### PR DESCRIPTION
**Pull request by nathanpiper**
Fix #1799.

### CODE REVIEW

**Comment by meltsufin** [comment]
@nathanpiper Thanks for the fix. Can you please sign the CLA?

**Review by JoeWang1127 — APPROVED** [review]

**Comment by nathanpiper** [comment]
Thanks for reviewing. I just realised my commits have the wrong email address. What’s the best way to fix this? Should I just close this PR, create a new one and reference this one?

**Comment by JoeWang1127** [comment]
I think you can change the email in the commits.

**Comment by nathanpiper** [comment]
Thanks, I have updated it now.

**Pull request merged**
