### PR TITLE
Empty change to check how unit tests run

### PR DESCRIPTION
**Pull request by suztomo**
Empty change to check how unit tests run

### CODE REVIEW

**Comment by suztomo** [comment]
Build And Test / unitTests (8) failed https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/50/checks?check_run_id=1103888830 

```
[ERROR] Failed to execute goal on project spring-cloud-gcp-kotlin-app-sample: Could not resolve dependencies for project
 com.google.cloud:spring-cloud-gcp-kotlin-app-sample:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at 
org.springframework.boot:spring-boot-starter-data-jpa:jar:2.4.0-SNAPSHOT -> org.hibernate:hibernate-core:jar:5.4.20.Final
 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.3 -> com.sun.istack:istack-commons-runtime:jar:3.0.11: Failed to read artifact 
descriptor for com.sun.istack:istack-commons-runtime:jar:3.0.11: Could not transfer artifact com.sun.istack:istack-commons-
runtime:pom:3.0.11 from/to central (https://repo.maven.apache.org/maven2): 
/home/runner/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.11/istack-commons-runtime-3.0.11.pom.part (No
 such file or directory) -> [Help 1]
```

**Comment by suztomo** [comment]
2nd run of "Build And Test / unitTests (8)" passed mvn install but failed to compile test https://github.com/GoogleCloudPlatform/spring-cloud-gcp/runs/1105851346

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min (Wall Clock)
[INFO] Finished at: 2020-09-12T13:18:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project spring-cloud-gcp-data-datastore: Compilation failure
[ERROR] /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/convert/TestDatastoreItemCollections.java:[110,31] no suitable method found for add(java.util.List<capture#1 of ?>)
[ERROR]     method java.util.Collection.add(java.util.List<java.lang.Byte>) is not applicable
[ERROR]       (argument mismatch; java.util.List<capture#2 of ?> cannot be converted to java.util.List<java.lang.Byte>)
[ERROR]     method java.util.List.add(java.util.List<java.lang.Byte>) is not applicable
[ERROR]       (argument mismatch; java.util.List<capture#2 of ?> cannot be converted to java.util.List<java.lang.Byte>)
[ERROR] -> [Help 1]
```

**Comment by suztomo** [comment]
@dzou (I see you committed the repository few weeks ago) Do you happen to know why the compilation error did not surface when you made the change?

**Comment by dzou** [comment]
> @dzou (I see you committed the repository few weeks ago) Do you happen to know why the compilation error did not surface when you made the change?

Hmm I'm not sure. The build sometimes breaks when changes are introduced upstream in our Spring dependencies (since we depend on snapshot versions) but this seems unrelated... Let me see if it breaks locally for me.

**Comment by dzou** [comment]
Ah yes, the breakage is happening locally for me too. That is odd; it probably must be a breaking API change upstream in Spring which somehow changed the types.

**Comment by suztomo** [comment]
@dzou Thank you for checking!

**Comment by dzou** [comment]
@suztomo - I created an issue for us to fix this, thanks for reporting this Tomo.

**Pull request closed without merging**
