### PR TITLE
Support publisher shutdown

### PR DESCRIPTION
**Pull request by JoeWang1127**
See https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/864.

Add `@PreDestroy` method to shutdown cached `Publisher` in `CachingPublisherFactory`.

### CODE REVIEW

**Review by elefeint — CHANGES_REQUESTED** [review]
Could you also try to add an integration test for this? I think the easiest way would be to take an existing integration test, get a `Publisher` instance from the template's `publish()` call, then initiate application shutdown (by autowiring an ApplicationContext). Then to try to publish a message on the already-shutdown `Publisher` should throw an exception from the client library - "Cannot publish on a shut-down publisher.".

**Comment by JoeWang1127** [comment]
> Could you also try to add an integration test for this? I think the easiest way would be to take an existing integration test, get a `Publisher` instance from the template's `publish()` call, then initiate application shutdown (by autowiring an ApplicationContext). Then to try to publish a message on the already-shutdown `Publisher` should throw an exception from the client library - "Cannot publish on a shut-down publisher.".

Thanks for the advice, will do.

**Review by elefeint — APPROVED** [review]
Thank you! Can you add this to the CHANGELOG, either in this PR or in a follow-up?

**Comment by JoeWang1127** [comment]
> Thank you! Can you add this to the CHANGELOG, either in this PR or in a follow-up?

I'll make the change in this PR, thanks.

**Pull request merged**
