### PR TITLE
chore: changes to resolve artifact not accessible due to spring release repo access change

### PR DESCRIPTION
**Pull request by zhumin8**
Fixes 3.x branch fails to compile ([example log](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/5087495824/jobs/9142914069?pr=1906)) because `org.springframework.experimental:spring-native-configuration` cannot be downloaded from spring-releases repository.

`repo.spring.io` anonymous access is removed as of [5/25](https://status.spring.io/incidents/rl38k61jk6hr?u=dlh63rhg824z).  

- The experimental Spring Native artifacts are now available from spring milestone repository.
Context: note on spring-native readme [here](https://github.com/spring-attic/spring-native/blob/main/README.adoc?#L7:~:text=In%20order%20to%20adapt%20to%20the%20permissions%20changes%20on%20https%3A//repo.spring.io/release/%2C%20Spring%20Native%20artifacts%20are%20now%20available%20from%20https%3A//repo.spring.io/milestone/%2C%20Gradle%20and%20Maven%20build%20configuration%20of%20projects%20depending%20on%20Spring%20Native%20should%20be%20updated%20accordingly.).
- Also backport #1910 for `docs/pom.xml` dependencies.

### CODE REVIEW

**Review by emmileaf — APPROVED** [review]
Thanks @zhumin8! 

Realizing that this PR will still be blocked on `docsCheck`, and https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1913 (backport) blocked on these compile issues - perhaps we could just include that fix into this PR together?

**Comment by zhumin8** [comment]
Backport of #1913 is failing because Spring 3.x is compiled by JAVA 17. will revert changes in [9c443c9](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1912/commits/9c443c95d58c14b12b6308bcfe1aaaa5322c4f41) and use #1907 instead. 

```
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (generate-configprops) on project spring-cloud-gcp-docs: An exception occured while executing the Java class. org/springframework/cloud/internal/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 -> [Help 1]
```

**Comment by zhumin8** [comment]
Reverted spring-cloud-build upgrade to 4.x, override inherited versions not in maven central when possible.
`spring-doc-resources` configured [here](https://github.com/spring-cloud/spring-cloud-build/blob/v3.1.7/pom.xml#L1063-L1071) is replaced with `spring-asciidoctor-backends` in newer versions [here](https://github.com/spring-cloud/spring-cloud-build/blob/v4.0.3/pom.xml#L1120-L1124).
Due to maven coordinate changes, version override is not possible. Use local zip proposed in #1907 instead. 
@meltsufin @emmileaf PTAL.

**Review by meltsufin — APPROVED** [review]

**Review by emmileaf — APPROVED** [review]
Ah, Java 17...sucks that we can't backport the upgrade to 4.0.3 afterall. Thanks for porting the local workaround here, and LGTM!

(I'm curious if there might be a way to apply the `spring-doc-resources` to `spring-asciidoctor-backends` switch in our pom while staying on spring-cloud-build 3.1.7, which could remove the need for the local install. Let's get this unblocked though and I can follow-up on this thought in a separate PR)

**Comment by zhumin8** [comment]
@emmileaf Thanks for looking into it. It should be possible. 
I'll merge this in as tmp fix to unblock for now.

**Pull request merged**
