### PR TITLE
(Cherrypick) Firestore emulator will use given project ID if present

### PR DESCRIPTION
**Pull request by dzou**
Cherrypick of https://github.com/spring-cloud/spring-cloud-gcp/pull/2625

Fixes #2514.

### CODE REVIEW

**Comment by dzou** [comment]
@mac2000 - Hey, I am cherrypicking your contribution made to our old repo in our new repo here as well.

Could you sign our Google CLA by responding to this PR with `@googlebot I consent.` ? Much appreciated.

**Comment by ttomsu** [comment]
Friendly ping, @mac2000

**Review by ttomsu — APPROVED** [review]

**Comment by mac2000** [comment]
@ttomsu  thank you without your mention I did not see all that in my mail somehow

if I understand everything correctly all I need is to leave a comment:

@googlebot I consent.

Hopefully, it will work 🙃

**Comment by mac2000** [comment]
@googlebot I consent

**Comment by dzou** [comment]
> @ttomsu thank you without your mention I did not see all that in my mail somehow
> 
> if I understand everything correctly all I need is to leave a comment:
> 
> @googlebot I consent.
> 
> Hopefully, it will work

Thank you!

**Pull request merged**
