### PR TITLE
deps: Update Java client library dependencies

### PR DESCRIPTION
**Pull request by lqiu96**
BEGIN_COMMIT_OVERRIDE 
chore(deps): update dependency org.apache.maven.plugins:maven-gpg-plugin to v3.2.5
 chore(deps): update dependency org.apache.maven.plugins:maven-gpg-plugin to v3.2.5
 chore(deps): update dependency org.awaitility:awaitility to v4.2.2
 chore(deps): update gapic-generator-java-bom.version to v2.43.0 (com.google.api:gapic-generator-java, com.google.api:gapic-generator-java-bom)
 fix(deps): update dependency com.google.cloud:libraries-bom to v26.44.0
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by lqiu96** [comment]
Seeing this error in the storage-sample CI job:
```
Error: 5:408 [ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.10.2:test (native-test) on project spring-cloud-gcp-storage-resource-sample: Execution of /opt/hostedtoolcache/graalvm-community-jdk-21.0.2_linux-x64_bin/21.0.2/x64/graalvm-community-openjdk-21.0.2+13.1/bin/native-image -cp /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/classes:/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/test-classes:/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/src/test/resources:/home/runner/.m2/repository/com/google/cloud/spring-cloud-gcp-starter-storage/5.5.1-SNAPSHOT/spring-cloud-gcp-starter-storage-5.5.1-SNAPSHOT.jar:/home/runner/.m2/repository/com/google/cloud/spring-cloud-gcp-starter/5.5.1-SNAPSHOT/spring-cloud-gcp-starter-5.5.1-SNAPSHOT.jar:/home/runner/.m2/repository/com/google/cloud/spring-cloud-gcp-core/5.5.1-SNAPSHOT/spring-cloud-gcp-core-5.5.1-SNAPSHOT.jar:/home/runner/.m2/repository/com/google/cloud/google-cloud-core/2.41.0/google-cloud-core-2.41.0.jar:/home/runner/.m2/repository/com/google/cloud/spring-cloud-gcp-autoconfigure/5.5.1-SNAPSHOT/spring-cloud-gcp-autoconfigure-5.5.1-SNAPSHOT.jar:/home/runner/.m2/repository/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar:/home/runner/.m2/repository/com/google/cloud/spring-cloud-gcp-storage/5.5.1-SNAPSHOT/spring-cloud-gcp-storage-5.5.1-SNAPSHOT.jar:/home/runner/.m2/repository/org/springframework/spring-context/6.1.11/spring-context-6.1.11.jar:/home/runner/.m2/repository/com/google/cloud/google-cloud-storage/2.41.0/google-cloud-storage-2.41.0.jar:/home/runner/.m2/repository/com/google/guava/guava/33.2.1-jre/guava-33.2.1-jre.jar:/home/runner/.m2/repository/com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar:/home/runner/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/runner/.m2/repository/com/google/errorprone/error_prone_annotations/2.29.2/error_prone_annotations-2.29.2.jar:/home/runner/.m2/repository/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar:/home/runner/.m2/repository/com/google/http-client/google-http-client/1.44.2/google-http-client-1.44.2.jar:/home/runner/.m2/repository/io/grpc/grpc-context/1.65.1/grpc-context-1.65.1.jar:/home/runner/.m2/repository/io/opencensus/opencensus-contrib-http-util/0.31.1/opencensus-contrib-http-util-0.31.1.jar:/home/runner/.m2/repository/com/google/http-client/google-http-client-jackson2/1.44.2/google-http-client-jackson2-1.44.2.jar:/home/runner/.m2/repository/com/google/http-client/google-http-client-gson/1.44.2/google-http-client-gson-1.44.2.jar:/home/runner/.m2/repository/com/google/api-client/google-api-client/2.6.0/google-api-client-2.6.0.jar:/home/runner/.m2/repository/commons-codec/commons-codec/1.16.1/commons-codec-1.16.1.jar:/home/runner/.m2/repository/com/google/oauth-client/google-oauth-client/1.36.0/google-oauth-client-1.36.0.jar:/home/runner/.m2/repository/com/google/http-client/google-http-client-apache-v2/1.44.2/google-http-client-apache-v2-1.44.2.jar:/home/runner/.m2/repository/com/google/apis/google-api-services-storage/v1-rev20240706-2.0.0/google-api-services-storage-v1-rev20240706-2.0.0.jar:/home/runner/.m2/repository/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/home/runner/.m2/repository/com/google/auto/value/auto-value-annotations/1.10.4/auto-value-annotations-1.10.4.jar:/home/runner/.m2/repository/com/google/cloud/google-cloud-core-http/2.41.0/google-cloud-core-http-2.41.0.jar:/home/runner/.m2/repository/com/google/http-client/google-http-client-appengine/1.44.2/google-http-client-appengine-1.44.2.jar:/home/runner/.m2/repository/com/google/api/gax-httpjson/2.51.0/gax-httpjson-2.51.0.jar:/home/runner/.m2/repository/com/google/cloud/google-cloud-core-grpc/2.41.0/google-cloud-core-grpc-2.41.0.jar:/home/runner/.m2/repository/com/google/api/gax/2.51.0/gax-2.51.0.jar:/home/runner/.m2/repository/com/google/api/gax-grpc/2.51.0/gax-grpc-2.51.0.jar:/home/runner/.m2/repository/io/grpc/grpc-inprocess/1.65.1/grpc-inprocess-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-alts/1.65.1/grpc-alts-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-grpclb/1.65.1/grpc-grpclb-1.65.1.jar:/home/runner/.m2/repository/org/conscrypt/conscrypt-openjdk-uber/2.5.2/conscrypt-openjdk-uber-2.5.2.jar:/home/runner/.m2/repository/io/grpc/grpc-auth/1.65.1/grpc-auth-1.65.1.jar:/home/runner/.m2/repository/com/google/auth/google-auth-library-credentials/1.24.0/google-auth-library-credentials-1.24.0.jar:/home/runner/.m2/repository/com/google/auth/google-auth-library-oauth2-http/1.24.0/google-auth-library-oauth2-http-1.24.0.jar:/home/runner/.m2/repository/com/google/api/api-common/2.34.0/api-common-2.34.0.jar:/home/runner/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/home/runner/.m2/repository/io/opencensus/opencensus-api/0.31.1/opencensus-api-0.31.1.jar:/home/runner/.m2/repository/com/google/api/grpc/proto-google-iam-v1/1.37.0/proto-google-iam-v1-1.37.0.jar:/home/runner/.m2/repository/com/google/protobuf/protobuf-java/3.25.3/protobuf-java-3.25.3.jar:/home/runner/.m2/repository/com/google/protobuf/protobuf-java-util/3.25.3/protobuf-java-util-3.25.3.jar:/home/runner/.m2/repository/io/grpc/grpc-core/1.65.1/grpc-core-1.65.1.jar:/home/runner/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/home/runner/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.24/animal-sniffer-annotations-1.24.jar:/home/runner/.m2/repository/io/perfmark/perfmark-api/0.27.0/perfmark-api-0.27.0.jar:/home/runner/.m2/repository/io/grpc/grpc-protobuf/1.65.1/grpc-protobuf-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-protobuf-lite/1.65.1/grpc-protobuf-lite-1.65.1.jar:/home/runner/.m2/repository/com/google/api/grpc/proto-google-common-protos/2.42.0/proto-google-common-protos-2.42.0.jar:/home/runner/.m2/repository/org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.jar:/home/runner/.m2/repository/com/google/api/grpc/proto-google-cloud-storage-v2/2.41.0-alpha/proto-google-cloud-storage-v2-2.41.0-alpha.jar:/home/runner/.m2/repository/com/google/api/grpc/grpc-google-cloud-storage-v2/2.41.0-alpha/grpc-google-cloud-storage-v2-2.41.0-alpha.jar:/home/runner/.m2/repository/com/google/api/grpc/gapic-google-cloud-storage-v2/2.41.0-alpha/gapic-google-cloud-storage-v2-2.41.0-alpha.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-sdk/1.37.0/opentelemetry-sdk-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-sdk-trace/1.37.0/opentelemetry-sdk-trace-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-sdk-logs/1.37.0/opentelemetry-sdk-logs-1.37.0.jar:/home/runner/.m2/repository/io/grpc/grpc-opentelemetry/1.65.1/grpc-opentelemetry-1.65.1.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-api/1.37.0/opentelemetry-api-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-context/1.37.0/opentelemetry-context-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-sdk-metrics/1.37.0/opentelemetry-sdk-metrics-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-api-incubator/1.40.0-alpha/opentelemetry-api-incubator-1.40.0-alpha.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-sdk-common/1.37.0/opentelemetry-sdk-common-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.37.0/opentelemetry-sdk-extension-autoconfigure-spi-1.37.0.jar:/home/runner/.m2/repository/io/opentelemetry/semconv/opentelemetry-semconv/1.25.0-alpha/opentelemetry-semconv-1.25.0-alpha.jar:/home/runner/.m2/repository/com/google/cloud/opentelemetry/exporter-metrics/0.31.0/exporter-metrics-0.31.0.jar:/home/runner/.m2/repository/com/google/cloud/google-cloud-monitoring/3.48.0/google-cloud-monitoring-3.48.0.jar:/home/runner/.m2/repository/com/google/api/grpc/proto-google-cloud-monitoring-v3/3.48.0/proto-google-cloud-monitoring-v3-3.48.0.jar:/home/runner/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/runner/.m2/repository/com/google/cloud/opentelemetry/shared-resourcemapping/0.31.0/shared-resourcemapping-0.31.0.jar:/home/runner/.m2/repository/io/opentelemetry/contrib/opentelemetry-gcp-resources/1.37.0-alpha/opentelemetry-gcp-resources-1.37.0-alpha.jar:/home/runner/.m2/repository/com/google/cloud/opentelemetry/detector-resources-support/0.31.0/detector-resources-support-0.31.0.jar:/home/runner/.m2/repository/org/checkerframework/checker-qual/3.45.0/checker-qual-3.45.0.jar:/home/runner/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.17.2/jackson-core-2.17.2.jar:/home/runner/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/runner/.m2/repository/io/grpc/grpc-api/1.65.1/grpc-api-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-netty-shaded/1.65.1/grpc-netty-shaded-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-util/1.65.1/grpc-util-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-stub/1.65.1/grpc-stub-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-googleapis/1.65.1/grpc-googleapis-1.65.1.jar:/home/runner/.m2/repository/io/grpc/grpc-xds/1.65.1/grpc-xds-1.65.1.jar:/home/runner/.m2/repository/io/opencensus/opencensus-proto/0.2.0/opencensus-proto-0.2.0.jar:/home/runner/.m2/repository/io/grpc/grpc-services/1.65.1/grpc-services-1.65.1.jar:/home/runner/.m2/repository/com/google/re2j/re2j/1.7/re2j-1.7.jar:/home/runner/.m2/repository/io/grpc/grpc-rls/1.65.1/grpc-rls-1.65.1.jar:/home/runner/.m2/repository/org/slf4j/slf4j-api/2.0.13/slf4j-api-2.0.13.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.3.2/spring-boot-starter-web-3.3.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter/3.3.2/spring-boot-starter-3.3.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot/3.3.2/spring-boot-3.3.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.3.2/spring-boot-autoconfigure-3.3.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.3.2/spring-boot-starter-logging-3.3.2.jar:/home/runner/.m2/repository/ch/qos/logback/logback-classic/1.5.6/logback-classic-1.5.6.jar:/home/runner/.m2/repository/ch/qos/logback/logback-core/1.5.6/logback-core-1.5.6.jar:/home/runner/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.23.1/log4j-to-slf4j-2.23.1.jar:/home/runner/.m2/repository/org/apache/logging/log4j/log4j-api/2.23.1/log4j-api-2.23.1.jar:/home/runner/.m2/repository/org/slf4j/jul-to-slf4j/2.0.13/jul-to-slf4j-2.0.13.jar:/home/runner/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/home/runner/.m2/repository/org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.3.2/spring-boot-starter-json-3.3.2.jar:/home/runner/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.17.2/jackson-databind-2.17.2.jar:/home/runner/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.17.2/jackson-annotations-2.17.2.jar:/home/runner/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.17.2/jackson-datatype-jdk8-2.17.2.jar:/home/runner/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.17.2/jackson-datatype-jsr310-2.17.2.jar:/home/runner/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.17.2/jackson-module-parameter-names-2.17.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.3.2/spring-boot-starter-tomcat-3.3.2.jar:/home/runner/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.26/tomcat-embed-core-10.1.26.jar:/home/runner/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.26/tomcat-embed-el-10.1.26.jar:/home/runner/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.26/tomcat-embed-websocket-10.1.26.jar:/home/runner/.m2/repository/org/springframework/spring-web/6.1.11/spring-web-6.1.11.jar:/home/runner/.m2/repository/org/springframework/spring-beans/6.1.11/spring-beans-6.1.11.jar:/home/runner/.m2/repository/io/micrometer/micrometer-observation/1.13.2/micrometer-observation-1.13.2.jar:/home/runner/.m2/repository/io/micrometer/micrometer-commons/1.13.2/micrometer-commons-1.13.2.jar:/home/runner/.m2/repository/org/springframework/spring-webmvc/6.1.11/spring-webmvc-6.1.11.jar:/home/runner/.m2/repository/org/springframework/spring-aop/6.1.11/spring-aop-6.1.11.jar:/home/runner/.m2/repository/org/springframework/spring-expression/6.1.11/spring-expression-6.1.11.jar:/home/runner/.m2/repository/org/awaitility/awaitility/4.2.2/awaitility-4.2.2.jar:/home/runner/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar:/home/runner/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/runner/.m2/repository/org/hamcrest/hamcrest-core/2.2/hamcrest-core-2.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-test/3.3.2/spring-boot-starter-test-3.3.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-test/3.3.2/spring-boot-test-3.3.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/3.3.2/spring-boot-test-autoconfigure-3.3.2.jar:/home/runner/.m2/repository/com/jayway/jsonpath/json-path/2.9.0/json-path-2.9.0.jar:/home/runner/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar:/home/runner/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar:/home/runner/.m2/repository/net/minidev/json-smart/2.5.1/json-smart-2.5.1.jar:/home/runner/.m2/repository/net/minidev/accessors-smart/2.5.1/accessors-smart-2.5.1.jar:/home/runner/.m2/repository/org/ow2/asm/asm/9.6/asm-9.6.jar:/home/runner/.m2/repository/org/assertj/assertj-core/3.25.3/assertj-core-3.25.3.jar:/home/runner/.m2/repository/net/bytebuddy/byte-buddy/1.14.18/byte-buddy-1.14.18.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter/5.10.3/junit-jupiter-5.10.3.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.10.3/junit-jupiter-api-5.10.3.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.10.3/junit-jupiter-params-5.10.3.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.10.3/junit-jupiter-engine-5.10.3.jar:/home/runner/.m2/repository/org/mockito/mockito-core/5.11.0/mockito-core-5.11.0.jar:/home/runner/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.18/byte-buddy-agent-1.14.18.jar:/home/runner/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar:/home/runner/.m2/repository/org/mockito/mockito-junit-jupiter/5.11.0/mockito-junit-jupiter-5.11.0.jar:/home/runner/.m2/repository/org/skyscreamer/jsonassert/1.5.3/jsonassert-1.5.3.jar:/home/runner/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar:/home/runner/.m2/repository/org/springframework/spring-core/6.1.11/spring-core-6.1.11.jar:/home/runner/.m2/repository/org/springframework/spring-jcl/6.1.11/spring-jcl-6.1.11.jar:/home/runner/.m2/repository/org/springframework/spring-test/6.1.11/spring-test-6.1.11.jar:/home/runner/.m2/repository/org/xmlunit/xmlunit-core/2.9.1/xmlunit-core-2.9.1.jar:/home/runner/.m2/repository/org/junit/vintage/junit-vintage-engine/5.10.3/junit-vintage-engine-5.10.3.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-engine/1.10.3/junit-platform-engine-1.10.3.jar:/home/runner/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-commons/1.10.3/junit-platform-commons-1.10.3.jar:/home/runner/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-launcher/1.10.3/junit-platform-launcher-1.10.3.jar:/home/runner/.m2/repository/org/graalvm/buildtools/native-maven-plugin/0.10.2/native-maven-plugin-0.10.2.jar:/home/runner/.m2/repository/org/graalvm/buildtools/utils/0.10.2/utils-0.10.2.jar:/home/runner/.m2/repository/org/graalvm/buildtools/graalvm-reachability-metadata/0.10.2/graalvm-reachability-metadata-0.10.2.jar:/home/runner/.m2/repository/org/graalvm/buildtools/junit-platform-native/0.10.2/junit-platform-native-0.10.2.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-console/1.10.0/junit-platform-console-1.10.0.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-reporting/1.10.0/junit-platform-reporting-1.10.0.jar:/home/runner/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-launcher/1.10.0/junit-platform-launcher-1.10.0.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-engine/1.10.0/junit-platform-engine-1.10.0.jar:/home/runner/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar:/home/runner/.m2/repository/org/junit/platform/junit-platform-commons/1.10.0/junit-platform-commons-1.10.0.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter/5.10.0/junit-jupiter-5.10.0.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.10.0/junit-jupiter-api-5.10.0.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.10.0/junit-jupiter-params-5.10.0.jar:/home/runner/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.10.0/junit-jupiter-engine-5.10.0.jar --no-fallback -o /home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/native-tests -Dgcs-local-directory=/tmp/gcp_integration_tests/integration_storage_sample -Dgcs-read-bucket=gcp-storage-bucket-sample-input -Dgcs-resource-test-bucket=gcp-storage-resource-bucket-sample -Dgcs-write-bucket=gcp-storage-bucket-sample-output -Dit.alloydb=true -Dit.bigquery=true -Dit.cloudsql=true -Dit.datastore=true -Dit.firestore=true -Dit.kms=true -Dit.logging=true -Dit.metrics=true -Dit.pubsub=true -Dit.pubsub-bus=true -Dit.pubsub-integration=true -Dit.secretmanager=true -Dit.spanner=true -Dit.storage=true -Dit.trace=true -Dit.vision=true -Djunit.platform.listeners.uid.tracking.output.dir=/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/test-ids -Dkms-test-encrypted-text=CiQA04Sv0lCnHhQQIwKI0XDU+XcU6q1ryy+VuQJ6oh6VF8eJRocSLgBVx+glEafbllCrwhS8utmM9RYAC80xizA/YYyjE/roXcRDj9AGpfTS3iDKg5E= -Dkms-test-project-id=spring-cloud-gcp-ci-native -Dspring.cloud.gcp.alloydb.database-name=code_samples_test_db -Dspring.cloud.gcp.alloydb.instance-connection-uri=projects/spring-cloud-gcp-ci-native/locations/us-central1/clusters/testcluster/instances/testpostgres -Dspring.cloud.gcp.sql.database-name=code_samples_test_db -Dspring.cloud.gcp.sql.instance-connection-name=spring-cloud-gcp-ci-native:us-central1:testmysql -Dspring.datasource.*** -Dspring.r2dbc.*** -H:ConfigurationFileDirectories=/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/graalvm-reachability-metadata/2ea75347f1ec75211e397713cc559ab15fd6fdec/org.mockito/mockito-core/4.8.1,/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/graalvm-reachability-metadata/2ea75347f1ec75211e397713cc559ab15fd6fdec/ch.qos.logback/logback-classic/1.4.9,/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/graalvm-reachability-metadata/2ea75347f1ec75211e397713cc559ab15fd6fdec/com.fasterxml.jackson.core/jackson-databind/2.15.2,/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/graalvm-reachability-metadata/2ea75347f1ec75211e397713cc559ab15fd6fdec/commons-logging/commons-logging/1.2,/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/graalvm-reachability-metadata/2ea75347f1ec75211e397713cc559ab15fd6fdec/org.apache.tomcat.embed/tomcat-embed-core/10.0.20,/home/runner/work/spring-cloud-gcp/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/target/graalvm-reachability-metadata/2ea75347f1ec75211e397713cc559ab15fd6fdec/com.google.protobuf/protobuf-java-util/3.21.12 --features=org.graalvm.junit.platform.JUnitPlatformFeature org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result -> [Help 1]
```

**Comment by mpeddada1** [comment]
Failure: `org.apache.commons.logging.LogFactory was unintentionally initialized at build time`

Using `--trace-class-initialization=org.apache.commons.logging.LogFactory,org.apache.commons.logging.LogFactoryService` locally shows that that the build time initialization is being caused by `org.springframework.beans.factory.support.DisposableBeanAdapter`:
```
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. org.springframework.beans.factory.support.DisposableBeanAdapter caused initialization of this class with the following trace: 
	at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:136)
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(Unknown Source)
	at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
	at java.lang.Class.newInstance(Class.java:725)
	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1047)
	at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
	at java.security.AccessController.executePrivileged(AccessController.java:778)
	at java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:552)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.<clinit>(DisposableBeanAdapter.java:76)

org.apache.commons.logging.LogFactoryService was unintentionally initialized at build time. org.springframework.beans.factory.support.DisposableBeanAdapter caused initialization of this class with the following trace: 
	at org.apache.commons.logging.LogFactoryService.<clinit>(LogFactoryService.java)
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(Unknown Source)
	at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
	at java.lang.Class.newInstance(Class.java:725)
	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1047)
	at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
	at java.security.AccessController.executePrivileged(AccessController.java:778)
	at java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:552)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.<clinit>(DisposableBeanAdapter.java:76)

```

**Comment by JoeWang1127** [comment]
`chore(deps): update dependency org.apache.maven.plugins:maven-gpg-plugin to v3.2.5` appears twice in the pr body.

**Comment by lqiu96** [comment]
Closing this as the deps have been merged in renovate bot PRs

**Pull request closed without merging**
