### PR TITLE
Renaming master branch to main

### PR DESCRIPTION
**Pull request by meltsufin**
Continuing #200 targeting merge to `master` before rename to `main`.

### CODE REVIEW

**Review by elefeint — APPROVED** [review]

**Comment by meltsufin** [comment]
@kioie Can you please sign the CLA or just consent? Thanks!

**Comment by kioie** [comment]
@googlebot I consent

**Comment by kioie** [comment]
> @kioie Can you please sign the CLA or just consent? Thanks!

Consented :thumbsup: I think I had also signed the CLA, how can I confirm?

**Comment by meltsufin** [comment]
> > @kioie Can you please sign the CLA or just consent? Thanks!
> 
> Consented 👍 I think I had also signed the CLA, how can I confirm?

@kioie We're good on that. Thanks!

**Comment by meltsufin** [comment]
@kioie Can you give me access to your fork? I want to push a couple of commits to this PR.

**Comment by kioie** [comment]
> @kioie Can you give me access to your fork? I want to push a couple of commits to this PR.

done

**Comment by kioie** [comment]
:+1:  important change :clap:

**Pull request merged**
