### PR TITLE
Add additional null checks for Spanner

### PR DESCRIPTION
**Pull request by dzou**
Add additional null checks for Spanner module.

### CODE REVIEW

**Review by elefeint — CHANGES_REQUESTED** [review]
There might be an opportunity here for a helper method/class that takes a spanner mapping context, and either retrieves persistent entity or throws.

**Comment by ttomsu** [comment]
+1 to Elena's comment - plus you may start getting dinged on repeating the same String and told to make it a constant

**Comment by dzou** [comment]
> There might be an opportunity here for a helper method/class that takes a spanner mapping context, and either retrieves persistent entity or throws.

Done -- I introduced a method called `context.getPersistentEntityOrFail(..)`

**Review by elefeint — APPROVED** [review]
You can even just make it an overridden version of `.getPersistentEntity()`. Failure is always an option for any method.

**Comment by dzou** [comment]
> You can even just make it an overridden version of `.getPersistentEntity()`. Failure is always an option for any method.

I tried to just override the `.getPersistentEntity()` directly at first, however it seems there times where we check if it is `null` or not; there was at least one test that failed. (I guess it's just the majority of cases (and not all) in which we call this method unsafely.)

**Pull request merged**
