### PR TITLE
Cherry-picks most recent commits from old repo

### PR DESCRIPTION
**Pull request by ttomsu**
**Please have a look through your commits below to confirm they look like they've gotten all of the changes you expect**

I ended up cherry-picking the commits from the most recent common ancestor from the old and new repos because we've started to diverge pretty heavily from the old branch. This seemed like the easiest way to:

* get all the commits
* be able to edit them along the way (a la `git rebase master -i`)
* skip the ones that don't apply

I think any work done on the old repo should start to get mirrored to the new repo, if not we outright start working exclusively in the new repo (AIUI, no additional releases are planned for Huxton?)

I ended up skipping the following commits from the old repo (between [2020-08-21's  c9614b8](https://github.com/spring-cloud/spring-cloud-gcp/commit/c9614b8299a4c2ffe5484969684562552f6256f4) and [2020-09-28's 4f939bf](https://github.com/spring-cloud/spring-cloud-gcp/commit/4f939bf9fe6f0249e0580a7067fe122de9b481b8))

* [Upgrade version numbers to 1.2.6](https://github.com/spring-cloud/spring-cloud-gcp/commit/6ed49d5951b4d4195c179a289c7f2889be3d67bb)
* [1.2.5 Release Notes](https://github.com/spring-cloud/spring-cloud-gcp/commit/5217e42d5bfff39ebc883db1b56c0e92133d64bd)

Found the most recent ancestor with:
```
$ git merge-base master old/master
c9614b8299a4c2ffe5484969684562552f6256f4

```

### CODE REVIEW

**Comment by ttomsu** [comment]
@ohardeng @gabac @romani Would you be opposed to signing the Google CLA so that we may use these commits in the official `GoogleCloudPlatform` repo and you get credit for them?

**Review by elefeint — APPROVED** [review]

**Comment by gabac** [comment]
> @ohardeng @gabac @romani Would you be opposed to signing the Google CLA so that we may use these commits in the official `GoogleCloudPlatform` repo and you get credit for them?

Should be signed 👍

**Comment by romani** [comment]
I did sign off already. Please use any my commit.

**Review by dzou — APPROVED** [review]

**Review by gabac — APPROVED** [review]

**Comment by ttomsu** [comment]
@googlebot I fixed it.

**Comment by ttomsu** [comment]
I'm going to disable the CLA check and submit this, per our conversation earlier. If you'd like us to remove your commit, please let us know.

**Comment by ohardeng** [comment]
> I'm going to disable the CLA check and submit this, per our conversation earlier. If you'd like us to remove your commit, please let us know.

Sorry, I've been on vacation. CLA signed and I'm happy to contribute

**Pull request merged**
