### PR TITLE
Allow setting maxFetchSize on polling stream binder

### PR DESCRIPTION
**Pull request by ttomsu**
Fixes https://github.com/spring-cloud/spring-cloud-gcp/issues/1432

### CODE REVIEW

**Comment by dzou** [comment]
Looks good. Maybe you can add a mention to the property in the [`pubsub-integration.adoc`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/95c692b4f63d62c9c9fa3c28caee386554b2b3f0/docs/src/main/asciidoc/spring-stream.adoc#configuration).

**Review by meltsufin — APPROVED** [review]
LGTM!

**Review by elefeint — APPROVED** [review]
Nice helper; will help it propagate more properties in the future.

**Comment by ttomsu** [comment]
@dzou Added mention of the property in the docs.

**Pull request merged**
