### PR TITLE
Datastore array conversion: turn array into a list with same elements

### PR DESCRIPTION
**Pull request by elefeint**
Pick your poison -- this PR fixes the logic, and #733 rips it out.

### CODE REVIEW

**Review by meltsufin — APPROVED** [review]
Would it make sense to also add an integration test and update docs?

**Comment by elefeint** [comment]
Is this something we *want* to support officially? None of our higher level code exercises this path, so integration test would have to be something fairly contrived.

**Comment by meltsufin** [comment]
I was thinking along the lines of exercising the feature in on of our sample apps.

**Comment by elefeint** [comment]
Closing in favor of #733.

**Pull request closed without merging**
